In [5]:
#Assigment 9

In [6]:
#Creating a numpy array and perform Various operations

In [7]:
import numpy as np

In [8]:
array1=np.array([1,2,3,4,5])

In [9]:
array2=([6,7,8,9,10])

In [ ]:
#Addition

In [10]:
arr_sum=array1+array2

In [11]:
arr_sum

array([ 7,  9, 11, 13, 15])

In [ ]:
#Subtraction

In [12]:
arr_diff=array1-array2

In [13]:
arr_diff

array([-5, -5, -5, -5, -5])

In [ ]:
#Multiplication

In [14]:
arr_product=array1*array2

In [15]:
arr_product

array([ 6, 14, 24, 36, 50])

In [ ]:
#Division

In [16]:
arr_division=array1/array2

In [17]:
arr_division

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
#Indexing and slicing

In [19]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200])

In [21]:
#Get 140
element_140=arr[-7]
element_140

140

In [23]:
#Get 70
element_70=arr[6]
element_70

70

In [24]:
#Get 40 to 100
element_40_100=arr[3:10]
element_40_100

array([ 40,  50,  60,  70,  80,  90, 100])

In [25]:
#get 10,30,50,70
element_jump=arr[0:8:2]
element_jump

array([10, 30, 50, 70])

In [28]:
#Get 10 t0 50
element_10_50=arr[:5]
element_10_50

array([10, 20, 30, 40, 50])

In [ ]:
#Reshaping arrays and transporsing matrices

In [31]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
array.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
array.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
array3=np.array([[2,4,6,8,10],[1,3,5,7,9]])
array3

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [43]:
transpose=array3.T
transpose

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [ ]:
#Statistics

In [44]:
my_array=np.array([5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100])

In [49]:
#Mean
mean=np.mean(my_array)
mean

52.5

In [50]:
median=np.median(my_array)
median

52.5

In [52]:
variance=np.var(my_array)
variance

831.25

In [53]:
std_dev=np.std(my_array)
std_dev

28.83140648667699

In [ ]:
#Array with different data types

In [54]:
#Array with integers
int_arr=np.array([2,3,4,5,6])
int_arr

array([2, 3, 4, 5, 6])

In [56]:
str_arr=np.array(['Sana','Muskan','Azalfa','Kainat','Hania','Abdul Hadi'])
str_arr

array(['Sana', 'Muskan', 'Azalfa', 'Kainat', 'Hania', 'Abdul Hadi'],
      dtype='<U10')

In [59]:
boolean_arr=np.array([True,False,False,True,False,True,True])
boolean_arr

array([ True, False, False,  True, False,  True,  True])

In [61]:
float_arr=np.array([0.1,0.2,0.3,0.4,0.5])
float_arr

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [ ]:
#Concatenation of array

In [65]:
array_1=np.array([1,2,3])
array_2=np.array([4,5,6])
concatenate_array=np.concatenate((array_1,array_2))
concatenate_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Sorting

In [68]:
arr_1=np.array([4,7,2,10,3,9,5,8,31,16,34,0])

In [70]:
#Ascending order
asc_arr=np.sort(arr_1)
asc_arr

array([ 0,  2,  3,  4,  5,  7,  8,  9, 10, 16, 31, 34])

In [76]:
#Descending_order
des_arr=np.sort(arr_1)[::-1]
des_arr

array([34, 31, 16, 10,  9,  8,  7,  5,  4,  3,  2,  0])